import type { LocationType } from './types';

export const locationsList: LocationType[] = [
  {
    id: 1,
    address_street: '826 Cottonwood Way',
    address_city: 'Largo',
    address_state: 'Florida',
    address_zip: '34643',
    address_name: 'MERCYONE HANSEN FAMILY HOSPITAL MEDICAL SHOP, LLC',
  },
  {
    id: 2,
    address_street: '53 Wayridge Parkway',
    address_city: 'Pensacola',
    address_state: 'Florida',
    address_zip: '32505',
    address_name: 'NORTH MISSISSIPPI MEDICAL CENTER INC',
  },
  {
    id: 3,
    address_street: '8 Summit Terrace',
    address_city: 'Jacksonville',
    address_state: 'Florida',
    address_zip: '32225',
    address_name: 'ST. BARNABAS HOSPITAL',
  },
  {
    id: 4,
    address_street: '42369 Prairie Rose Avenue',
    address_city: 'Jacksonville',
    address_state: 'Florida',
    address_zip: '32225',
    address_name: 'CLEARSKY REHABILITATION HOSPITAL OF HARKER HEIGHTS, LLC',
  },
  {
    id: 5,
    address_street: '759 Delladonna Trail',
    address_city: 'Fort Myers',
    address_state: 'Florida',
    address_zip: '33913',
    address_name: 'KAISER PERMANENTE MEDICAL CENTER',
  },
  {
    id: 6,
    address_street: '7800 Norway Maple Place',
    address_city: 'Boynton Beach',
    address_state: 'Florida',
    address_zip: '33436',
    address_name: 'PULLMAN REGIONAL HOSPITAL',
  },
  {
    id: 7,
    address_street: '3210 5th Circle',
    address_city: 'Orlando',
    address_state: 'Florida',
    address_zip: '32891',
    address_name: 'SHARP MEMORIAL HOSPITAL',
  },
  {
    id: 8,
    address_street: '388 Hagan Crossing',
    address_city: 'Kissimmee',
    address_state: 'Florida',
    address_zip: '34745',
    address_name: 'COVENANT MEDICAL CENTER INC',
  },
  {
    id: 9,
    address_street: '57251 Elgar Drive',
    address_city: 'Pensacola',
    address_state: 'Florida',
    address_zip: '32575',
    address_name: 'SANFORD MEDICAL CENTER PHARMACY',
  },
  {
    id: 10,
    address_street: '36628 Russell Park',
    address_city: 'West Palm Beach',
    address_state: 'Florida',
    address_zip: '33416',
    address_name: 'EAST MORGAN COUNTY HOSPITAL',
  },
];
